### ISSUE TITLE
In the AAPCS64 the purpose of the 4 member limit on Homogeneous Aggregates is not explained

### ISSUE THREAD

**Issue by DavidSpickett** [ARM-software/abi-aa#102]
I'm working on something for llvm that deals with assigning register blocks to HFA/HVA types and what we currently do
is if the number of members is >8 it goes on the stack. (if we assume it's the only parameter)

So a struct of 8 doubles goes in registers, 9 doubles goes on the stack. Makes sense since the number of argument registers is 8 per class of register.

This agrees with "Stage C – Assignment of arguments to registers and stack" rule C2.
(https://github.com/ARM-software/abi-aa/blob/2bcab1e3b22d55170c563c3c7940134089176746/aapcs64/aapcs64.rst#parameter-passing-rules)

However if you look at the definition of HFA/HVA it limits them to 4 members (presumably at any depth, so counting nested structs and arrays).
https://github.com/ARM-software/abi-aa/blob/2bcab1e3b22d55170c563c3c7940134089176746/aapcs64/aapcs64.rst#homogeneous-aggregates

"An Homogeneous Floating-point Aggregate (HFA) is an Homogeneous Aggregate with a Fundamental Data Type that is a Floating-Point type and at most four uniquely addressable members."

I don't see this limitation referenced anywhere else in the document, is there a justification for this rule?
(if there is I don't think it's being applied correctly with clang)

Some ideas I had:
* this is a hold over (or compatibility feature) from the 32 bit ABI where there are only 4 argument registers
* there is a very specific meaning to "uniquely addressable" (but I didn't find any specific definition so I assume it means anything that isn't a bitfield?)
* the 4 member limit is correct but there is another rule that I have missed that means it doesn't apply to parameter passing

**Comment by DavidSpickett** [comment]
Also does this member limit apply recursively? If it is to be used to assign registers then presumably it must.

struct Foo { double d1; double d2; };
struct Bar { Foo f1; Foo f2; Foo f3; Foo f4; };

The above "Bar" would have 4 members if you just take the first level, but 8 if you walk the whole type. So it would need 8 registers, assuming such a type is in fact, an HFA.

**Comment by DavidSpickett** [comment]
It was suggested to me that the 4 member limit is a compromise to make sure there is room for other parameters. As in, why waste all 8 parameter registers on a struct where only part of it might be used.

This makes a lot of sense to me and fits with gcc and clang's output: https://godbolt.org/z/Ezhs7sjTo

**Comment by rearnsha** [comment]
I fear the reasoning is probably lost in the mists of time.  IIRC, it was a rule that was carried forward from the ATPCS into the AArch32 AAPCS and then into the AArch64 version, since there seemed no good reason to have different rules.

**Comment by rearnsha** [comment]
I think this issue should be closed.  The AAPCS documents are not rationale documents and would be confusingly bloated if such material were added.

**Comment by DavidSpickett** [comment]
SGTM
