### ISSUE TITLE
Pass `-c` to rst2pdf to compress the PDF files

### ISSUE THREAD

**Issue by Kristine1975** [ARM-software/abi-aa#119]
Passing `-c` (or `--compressed`) to rst2pdf would make it compress the PDFs, which would reduce their size by about 80%:

https://github.com/ARM-software/abi-aa/blob/8b9c82e05759f46ff1d65e5f4acec78327bf188c/tools/rst2pdf/generate-pdfs.sh#L48

Granted, the savings are only a few MBs for all PDFs together...

**Comment by stuij** [comment]
Thanks @Kristine1975 :) Willdo.

**Comment by stuij** [comment]
implemented by above pull request, so closing.

Thanks again @Kristine1975.
