### ISSUE TITLE
Please mention that C/C++ language binding is in the same document

### ISSUE THREAD

**Issue by Kristine1975** [ARM-software/abi-aa#126]
[Section 5.3.4 of the AAPCS 32 bit](https://github.com/ARM-software/abi-aa/blob/d6e9abbc5e9cdcaa0467d8187eec0049b44044c4/aapcs32/aapcs32.rst#bit-fields) ends with:

> The layout of bit-fields within an aggregate is defined by the appropriate language binding.

Please add a note that for C/C++ this language binding is in [section 8 of the very same document](https://github.com/ARM-software/abi-aa/blob/d6e9abbc5e9cdcaa0467d8187eec0049b44044c4/aapcs32/aapcs32.rst#arm-c-and-c-language-mappings), so it's easier to find.

**Comment by stuij** [comment]
closing. fixed by https://github.com/ARM-software/abi-aa/pull/132
