### ISSUE TITLE
[ehabi32] Fix "trade off"

### ISSUE THREAD

**Issue by vhscampos** [ARM-software/abi-aa#143]
"trade off" is not a correct term. It should be either "tradeoff" or "trade-off"

**Comment by rearnsha** [comment]
Well that depends on the context of its use.  If it's used as a verb then "trade off" is clearly correct.  But if used as a noun then you're correct.

**Comment by vhscampos** [comment]
It's used as a noun. It's in the second paragraph of Section 3.
