### ISSUE TITLE
Is page-size part of the ABI ?

### ISSUE THREAD

**Issue by gonzalobg** [ARM-software/abi-aa#198]
The Emacs package assumes that the page size in the system where it is built will be the same as in the system where it is deployed.

The Emacs package in Ubuntu 22.04 therefore fails to install on systems with 64 KB page size.

I could not find any mention of page size being or not being part of the Linux ABI for arm64.

1. If it is not part of the ABI, then Emacs has a bug, for making an assumption that the ABI does not allow portable Linux software to make.
2. If it is part of the ABI, then the Ubuntu distribution has a bug, e.g.,
    1.  for distributing binaries built on a system with a 4 KB page size to installations configured to use 64 KB pages, or
    2. should document that Ubuntu shall not be used on systems with 64 KB pages.

Specifying the requirements for proper software interoperation is the job of the platform ABI. I think the Linux Arm64 ABI should explicitly call out whether the page-size is or is not part of the ABI, since that would make it clear where the bug is.

See [https://lists.gnu.org/archive/html/bug-gnu-emacs/2021-03/msg01275.html](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Flists.gnu.org%2Farchive%2Fhtml%2Fbug-gnu-emacs%2F2021-03%2Fmsg01275.html&data=05%7C01%7Cgonzalob%40nvidia.com%7C23d0fdd507454583654608db322ad8d0%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C638158931831629287%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QcPGvwtZm3PUm9Gxde1W%2BqbQMCLSIVxM72b8D1J39SM%3D&reserved=0).

**Comment by smithp35** [comment]
The closest we have in the processor specific ABI is https://github.com/ARM-software/abi-aa/blob/main/sysvabi64/sysvabi64.rst#9program-loading-and-dynamic-linking 
```
Since the architecture supports a maximum page size of 64KiB the page size should be set to 64KiB for compatibility with systems that use 64KiB pages.
```
Essentially for maximum compatibility across distributions the recommendation is to use 64KiB page size. The default for LLD and ld.bfd is set to 64KiB.

Platforms such as Linux distributions are free to have their own platform ABI that deviates from this though. I fear that in the case of page-size historical precedent is likely to mean that Distros that have chosen 4KiB will be unwilling to switch whatever is written in the processor ABI.
