### ISSUE TITLE
vfabi: inactive lanes of the returned vector are not specified

### ISSUE THREAD

**Issue by nsz-arm** [ARM-software/abi-aa#2]
inbranch vector calls get a mask argument so the call only operates on active lanes according to that mask, but the abi does not say what happens with the inactive lanes in the returned vector.

i think it should explicitly say that inactive lanes have unspecified value in the returned vector.

**Comment by fpetrogalli** [comment]
We can either set the inactive lanes of the return value as zero or as undef.

@rsandifo-arm, you mentioned you think it is better to use undef, for the following reasons:

1. It seems more robust if callees don't rely on the caller to zero inactive lanes, just like current
callees don't rely on callers to zero the upper bits of an unsigned int parameter passed in an X register.

2. guaranteeing that the inactive lanes of outputs are zero when the inputs might not be would usually require an explicit, easy-to-forget zeroing step.

Your arguments seem to cover for input registers though, not the output?

**Comment by rsandifo-arm** [comment]
Yeah, (1) was supposed to cover inputs: callees shouldn't make any assumptions about what the caller has provided for inactive lanes, so inactive lanes are effectively undef on input.  (2) is then about the effect this has on the outputs: if callees don't make any assumptions about the inactive lanes of inputs, they would need to insert an explicit zeroing step if they had to provide guaranteed inactive values for outputs.  This would usually require a MOVPRFX and would be easy to forget.

So I think the inactive lanes should be undef for both inputs and outputs.

**Comment by nsz-arm** [comment]
note that gcc currently implements the intel vector abi, which has

> For each element of the vector, if the corresponding mask value is zero, the return value associated to that element is zero.

using undef instead of zero means that the mask can be ignored, i.e. `_ZGVnM* ` could be an alias of `_ZGVnN*`, not sure if that's good for advsimd.

**Comment by fpetrogalli** [comment]
> using undef instead of zero means that the mask can be ignored,

@nsz-arm , how do you get to this conclusion? It seems to me that the mask can be ignored if and only if all the logical lanes are inactive?

**Comment by nsz-arm** [comment]
> > using undef instead of zero means that the mask can be ignored,
> 
> @nsz-arm , how do you get to this conclusion? It seems to me that the mask can be ignored if and only if all the logical lanes are inactive?

if inactive lane can be anything on return then the return value of an unmasked operation is valid for a masked operation with arbitrary mask.

on a second thought this is not very important, but alignment with intel vector abi (and its existing implementation and expectations) is a more important issue.

**Comment by rsandifo-arm** [comment]
> if inactive lane can be anything on return then the return value of an unmasked operation is valid for a masked operation with arbitrary mask.

Yeah, if the operation is free of side-effects, it should IMO be valid to use unpredicated/unmasked operations for inbranch functions.  Whether the function does that or not would be an optimisation decision for it to make.

And from an SVE point of view, that's a nice feature to have.  It means that it's possible to use side-effect-free unpredicated instructions even for inbranch functions.  It also means that it's possible to use _x ACLE functions.

> on a second thought this is not very important, but alignment with intel vector abi (and its existing implementation and expectations) is a more important issue.

I'm just worried that this will be too easy to forget.  For SVE, merging is really the predominant choice of predication, with zeroing being something you use an extra prefix for.  (There are exceptions.)

In practice, autovectorised SVE callers won't normally care what values are in the inactive lanes of the result.  So I can imagine the combination of the callee accidentally leaving a nonzero value in an inactive lane combined with a caller (unusually) relying on that lane being zero would end up being a hard-to-track down bug that is likely only to be picked up in the field.

**Comment by fpetrogalli** [comment]
@nsz-arm , @rsandifo-arm , I have created a PR here but I am unable to formally add you as reviewers. Please take a look at the (trivial) patch.

https://github.com/ARM-software/software-standards/pull/12

**Comment by fpetrogalli** [comment]
Resolved by https://github.com/ARM-software/abi-aa/pull/12
