### ISSUE TITLE
Procedure call standard allows LDM/STM for volatile access even when inappropriate.

### ISSUE THREAD

**Issue by rcls** [ARM-software/abi-aa#89]
Re "Procedure Call Standard for the Arm Architecture", section "8.1.5 Volatile Data Types".

The final paragraph appears to be poorly worded, and read pedantically, allows the use of LDM & STM instructions for volatile accesses on processors even where that is not correct. I believe on some Cortex-M series, those instructions need to be avoided for volatile accesses, as they may be restarted after an exception and repeat an access.

The paragraph contains the sentence
> The only guarantee applying to volatile types in these circumstances are that each byte of the type shall be accessed exactly once for each access mandated above, and that any bytes containing volatile data that lie outside the type shall not be accessed."

However, the "circumstances" is, in my reading, given by the previous sentence (regarding restrictions on bus width), and so the requirement applies only for restricted bus width.

For 32-bit volatile accesses on a 32-bit bus, the "accessed exactly once" then does not apply and nothing in the text stops the compiler from using LDM and STM incorrectly. For a 64-bit volatile access, the text appears to be recommending LDM / STM, as these satisfy the final sentence.

I think two changes are warranted:

1. Reword the sentence quoted above so that exactly-the-correct-bytes-exactly-once language applies in all circumstances.
2. Reword the third sentence (regarding a single instruction), to make it clear that using a single instruction is mandatory where an appropriate one is available, not just a suggestion ("should").
3. But sort out which requirements take priority.

As ARM pointed out in private email, we do not want to rule out LDM / STM on processors where they are safe. (E.g., volatile int64_t access on a Cortex-A series.) I presume a compile time decision not a runtime decision! Possibly even on Cortex-M we should allow LDM / STM for Cortex-M 64-bit accesses, and leave it to the programmer to split into 2 × 32-bit where necessary?

(Another corner case on the instructions used is based on the data-type. On a 32-bit processor with 64-bit floating point, one option is to use FP instructions for volatile uint64_t access. I'm guessing we don't want to end up requiring compilers do that on DPFP Cortex-M? Or do we....)

**Comment by rearnsha** [comment]
My personal feeling is that the wording here does not need to be changed.  Anybody implementing tools that support the AAPCS, or hand-writing assembler code is expected to have a full knowledge of the Arm architecture and it would be quite dangerous to start trying to describe caveats for that here.
For example, although use of STM or LDM with _multiple_ transfer registers is unsafe, there are no issues with transferring a _single_ register, provided the address used is 32-bit aligned.

**Comment by rcls** [comment]
Re

> Anybody implementing tools .... or hand-writing assembler code

There are other consumers of the AAPCS - I was referring to it in order to reason about the possible behaviours of C code, independently of a particular tool chain.

On `volatile` in particular, it seems the ISO C standard leaves the details of the behaviour largely up the implementation, and that the AAPCS is the appropriate part of the implementation definition to document that (for ARM procesors).

Re
> use of STM or LDM ... there are no issues with transferring a single register, provided the address used is 32-bit aligned

No-one was suggesting that the AAPCS should ban the use of LDM & STM for volatile in the cases where it is safe. The discussion of any actual changes to the text was in terms of program behaviour, not the specific instructions used.

**Comment by rearnsha** [comment]
> Re
> 
> > Anybody implementing tools .... or hand-writing assembler code
> 
> There are other consumers of the AAPCS - I was referring to it in order to reason about the possible behaviours of C code, independently of a particular tool chain.
> 
> On `volatile` in particular, it seems the ISO C standard leaves the details of the behaviour largely up the implementation, and that the AAPCS is the appropriate part of the implementation definition to document that (for ARM procesors).

And the AAPCS in turn defers that to the Arm ARM, which is the canonical source of how instructions behave in the architecture.

> 
> Re
> 
> > use of STM or LDM ... there are no issues with transferring a single register, provided the address used is 32-bit aligned
> 
> No-one was suggesting that the AAPCS should ban the use of LDM & STM for volatile in the cases where it is safe. The discussion of any actual changes to the text was in terms of program behaviour, not the specific instructions used.

The AAPCS is not a tutorial on writing Arm assembler.  Trying to call out specific instructions like this would be extremely dangerous because it could lead to errors by omission - for example, failure to mention VLDM and VSTM and then a whole bunch of AdvSIMD instructions.  The result would be a long (probably incomplete) list of instructions that might not be safe to use depending on the precise context; and that would just lead to a lack of overall clarity of the document as a whole.

**Comment by rcls** [comment]
> And the AAPCS in turn defers that to the Arm ARM, which is the canonical source of how instructions behave in the architecture.

But do the Arm ARMs have an adequate specification of the architecture-specific details of the C `volatile` keyword though? - the ISO C spec appears to deliberately leave much of this open. (If that is indeed covered in the ARM documents, then that may be a better place.)

>  The AAPCS is not a tutorial on writing Arm assembler. Trying to call out specific instructions like this would be extremely dangerous because it could lead to errors by omission 

Once again, no-one here is suggesting that the AAPCS should call out specific instructions. I am not asking for a tutorial on writing Arm assembler. The issue is the architecture-specific parts of the semantics of the C language.

The issue here is the parts of the behaviour of the C `volatile` keyword that are specific to Arm architectures, as long as appropriate behaviour of C code is achieved, I totally agree that it is out-of-scope which particular choice of instructions is made.
